version: '3.8'
services:
  mongo:
    image: mongo:6.0.5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: wooman
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234