version: '3.8'

services:
  mongo1:
    image: mongo:6.0.5
    hostname: mongo1
    container_name: mongo1
    restart: always
    environment:
      MONGO_INITDB_DATABASE: wooman
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017
    volumes:
      - ./data/db/replica/mongo1:/data/db
      - ./mongodb.key:/etc/mongodb.key
    command:
      - '--replSet'
      - 'myReplicaSet'
      - '--keyFile'
      - '/etc/mongodb.key'
      - '--bind_ip_all'
  mongo2:
    image: mongo:6.0.5
    hostname: mongo2
    container_name: mongo2
    restart: always
    environment:
      MONGO_INITDB_DATABASE: wooman
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    depends_on:
      - mongo1
    ports:
      - 27018:27018
    volumes:
      - ./data/db/replica/mongo2:/data/db
      - ./mongodb.key:/etc/mongodb.key
    command:
      - '--replSet'
      - 'myReplicaSet'
      - '--keyFile'
      - '/etc/mongodb.key'
      - '--bind_ip_all'
      - '--port'
      - '27018'
networks:
  default:
    name: mongoCluster